#!/bin/bash

echo "Updating repo..."
rm kawaii-testing.db
rm kawaii-testing.db*.sig
rm kawaii-testing.db.tar.gz
rm kawaii-testing.files
rm kawaii-testing.files*.sig
rm kawaii-testing.files.tar.gz

echo "repo-add"
repo-add --verify --sign kawaii-testing.db.tar.gz *.pkg.tar.zst


if [ $? -eq 0 ]
then
    echo "Repo updated successfully!"
else
    echo "Error! Could not update repo" >&2
fi

rm kawaii-testing.db
rm kawaii-testing.files
rm kawaii-testing.files.sig
rm kawaii-testing.db.sig
cp kawaii-testing.db.tar.gz kawaii-testing.db
cp kawaii-testing.files.tar.gz kawaii-testing.files
cp kawaii-testing.files.tar.gz.sig kawaii-testing.files.sig
cp kawaii-testing.db.tar.gz.sig kawaii-testing.db.sig

git add --all
COMMENT=a
git commit -m "$COMMENT"
git push
